#!/bin/bash -e

if [[ $DEBUG -ne 0 ]]; then
	set -x;
fi

# Let's put stdout as a log file
exec 3>&1
exec &>> /var/log/metal3-cni.log

readonly network_configuration=$(</dev/stdin)
case "$CNI_COMMAND" in
ADD)
	readonly cni_version=$(jq -r ".cniVersion" <<< "$network_configuration")
	readonly name=$(jq -r ".name" <<< "$network_configuration")
	readonly bridge=$(jq -r ".bridge" <<< "$network_configuration")
	echo "$bridge"
	readonly args=$(jq -r ".args" <<< "$network_configuration")

	if [[ -n "$PROV_CIDR" ]] && [[ -n "$EXT_CIDR" ]]; then
		readonly prov_iface_cidr="$PROV_CIDR"
		readonly ext_iface_cidr="$EXT_CIDR"
		if [[ -n "$PROV_GW" ]]; then
			readonly prov_iface_gw="$PROV_GW"
		else
			readonly ext_iface_gw="$EXT_GW"
		fi
	else
		IFS=":" read -r -a findpaths <<< "$CNI_PATH"
		readonly host_local_bin="$(find "${findpaths[@]}" -maxdepth 1 -type f -name host-local -executable | head -1)"
		readonly ipam_result=$(echo "$network_configuration" | "$host_local_bin")
		readonly ipam_code=$(jq -r '.code' <<< "$ipam_result")
		if [[ "$ipam_code" != "null" ]]; then
			>&3 echo "$ipam_result"
			exit 1
		fi

		readonly prov_iface_cidr=$(jq -r '.ips[0].address' <<< "$ipam_result")
		if [[ $prov_iface_cidr =~ ^[0-9]+(\.[0-9]*){3}/[0-9]+$  ]]; then
			readonly prov_ip_family=4
		else
			readonly prov_ip_family=6
		fi
		readonly prov_iface_gw=$(jq -r '.ips[0].gateway' <<< "$ipam_result")

		readonly ext_iface_cidr=$(jq -r '.ips[1].address' <<< "$ipam_result")
		if [[ $ext_iface_cidr =~ ^[0-9]+(\.[0-9]*){3}/[0-9]+$ ]]; then
			readonly ext_ip_family=4
		else
			readonly ext_ip_family=6
		fi
		readonly ext_iface_gw=$(jq -r '.ips[1].gateway' <<< "$ipam_result")
	fi

	if [[ -n "$CNI_EXTRA_ARGS" ]]; then
		eval "$CNI_EXTRA_ARGS"
	fi
	readonly prov_ifname="$CNI_IFNAME"

	# Set netns link for iproute
	mkdir -p /var/run/netns
	ln -sfT "$CNI_NETNS" "/run/netns/${CNI_CONTAINERID}"

	# Provisioning network
	readonly tmp_port_name="$(head -c 10 <<< "$CNI_CONTAINERID")"
	ip link add "m3ph${tmp_port_name}" type veth peer name "m3c${tmp_port_name}"
	ip link set "m3c${tmp_port_name}" netns "$CNI_CONTAINERID"
	port_addition_args=("$bridge" "m3ph$tmp_port_name")
	if [[ -n "$PROV_VLAN" ]]; then
		port_addition_args+=("tag=$PROV_VLAN")
	fi
	ovs-vsctl add-port "${port_addition_args[@]}"
	ip netns exec "$CNI_CONTAINERID" ip link show
	ip netns exec "$CNI_CONTAINERID" ip link set "m3c$tmp_port_name" name "$prov_ifname"
	ip netns exec "$CNI_CONTAINERID" ip link show
	ip netns exec "$CNI_CONTAINERID" ip addr add "$prov_iface_cidr" dev "$prov_ifname"
	ip netns exec "$CNI_CONTAINERID" ip link show

	ip netns exec "$CNI_CONTAINERID" ip link set "$prov_ifname" up
	ip link set "m3ph${tmp_port_name}" up
	if [[ "$prov_iface_gw" != "null" && "$prov_iface_gw" != "" ]]; then
		ip netns exec "$CNI_CONTAINERID" ip route add default via "$prov_iface_gw" dev "$prov_ifname"
	fi
	ip netns exec "$CNI_CONTAINERID" ip link show

	# External network
	# Compute bigger ifname
	[[ $CNI_IFNAME =~ (.*[^0-9])([0-9]+)$ ]] && readonly ext_ifname="${BASH_REMATCH[1]}$((BASH_REMATCH[2] + 1))"

	# Create veth pair and move container end to container netns
	ip link add "m3eh${tmp_port_name}" type veth peer name "m3c${tmp_port_name}"
	ip link set "m3c${tmp_port_name}" netns "$CNI_CONTAINERID"

	# Add host side to ovs
	port_addition_args=("$bridge" "m3eh$tmp_port_name")
	if [[ -n "$EXT_VLAN" ]]; then
		port_addition_args+=("tag=$EXT_VLAN")
	fi
	ovs-vsctl add-port "${port_addition_args[@]}"

	ip netns exec "$CNI_CONTAINERID" ip link show
	ip netns exec "$CNI_CONTAINERID" ip link set "m3c$tmp_port_name" name "$ext_ifname"
	ip netns exec "$CNI_CONTAINERID" ip addr add "$ext_iface_cidr" dev "$ext_ifname"

	ip netns exec "$CNI_CONTAINERID" ip link set "$ext_ifname" up
	ip link set "m3eh${tmp_port_name}" up
	if ! ip netns exec "$CNI_CONTAINERID" ip route show | grep default && [[ "$ext_iface_gw" != "null" && "$ext_iface_gw" != "" ]]; then
		ip netns exec "$CNI_CONTAINERID" ip route add default via "$ext_iface_gw" dev "$ext_ifname"
	fi
	ip netns exec "$CNI_CONTAINERID" ip link show


	# Gather macs for results
	readonly prov_iface_mac="$(ip netns exec "$CNI_CONTAINERID" ip link show "$prov_ifname" | awk '/ether/ {print $2}')"
	readonly ext_iface_mac="$(ip netns exec "$CNI_CONTAINERID" ip link show "$ext_ifname" | awk '/ether/ {print $2}')"
	tee >(cat >&3) << EOF  # Making sure that it gets printed both to the log and to the 3rd file descriptor
{
  "cniVersion": "0.4.0",
  "interfaces": [
    {
      "name": "$prov_ifname",
      "mac": "$prov_iface_mac",
      "sandbox": "$CNI_NETNS"
    },
    {
      "name": "$ext_ifname",
      "mac": "$ext_iface_mac",
      "sandbox": "$CNI_NETNS"
    }
  ],
  "ips": [
    {
      "version": "$prov_ip_family",
      "address": "$prov_iface_cidr",
      "gateway": "$prov_iface_gw",
      "interface": 0
    },
    {
      "version": "$ext_ip_family",
      "address": "$ext_iface_cidr",
      "gateway": "$ext_iface_gw",
      "interface": 1
    }
  ]
}
EOF

;;

DEL)
	readonly bridge=$(jq -r ".bridge" <<< "$network_configuration")
	readonly tmp_port_name="$(head -c 10 <<< "$CNI_CONTAINERID")"
	ovs-vsctl del-port "$bridge" "m3ph${tmp_port_name}"
	ovs-vsctl del-port "$bridge" "m3eh${tmp_port_name}"

	# Deallocate
	IFS=":" read -r -a findpaths <<< "$CNI_PATH"
	readonly host_local_bin="$(find "${findpaths[@]}" -maxdepth 1 -type f -name host-local -executable | head -1)"
	readonly ipam_result=$(echo "$network_configuration" | "$host_local_bin")
;;

GET)
	echo "NOT SUPPORTED"
	exit 1
;;

CHECK)
	# TODO: Use prevResult to check if the networking is as expected
;;

VERSION)
	tee >(cat >&3) << EOF
{
  "cniVersion": "0.4.0",
  "supportedVersions": ["0.3.0", "0.3.1", "0.4.0" ]
}
EOF

;;
esac
